### ISSUE TITLE
MS bot with Ms teams channel gives 400 error

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/BotBuilder-MicrosoftTeams#124]
I have  V3 BOT with Microsoft teams channel. I see following sporadic issue where it seems like teams is failing send response back to bot via **serviceURL** 

```
Error: POST to 'https://smba.trafficmanager.net/amer-client-ss.msg/v3/conversations/a%3A1qNZgTUu4ASGZkGKPYDtZque7ucUYmAuWHi7pVx2qfw7gtuHtEUybWEJnQDeZl31zAcglGMyoxKUik-VOpLKqGXop4UFTiQ70NZzkj49LHhNSeVlYFnJTCAjVVFtoViDt/activities/1529002753254' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:559:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
``

**Comment by billbliss** [comment]
@rjgmail88 what's the AppId of your bot?

**Comment by rjgmail88** [comment]
There are 2 BOTS. Above error is for BOT ID#984ede7e-bc35-4767-a19b-60a2d6c5e4be
Another bot is bc6873dc-1736-40be-98cc-b55df64647b4

**Comment by rjgmail88** [comment]
Has anything change ? I am seeing 502 and bot is completely down in production. Please advice asap if you can. We have a outage.  

```
Error: POST to 'https://smba.trafficmanager.net/amer-client-ss.msg/v3/conversations/a%3A1qNZgTUu4ASGZkGKPYDtZque7ucUYmAuWHi7pVx2qfw7gtuHtEUybWEJnQDeZl31zAcglGMyoxKUik-VOpLKqGXop4UFTiQ70NZzkj49LHhNSeVlYFnJTCAjVVFtoViDt/activities/1529075330199' failed: [**502**] Bad Gateway
```

**Comment by billbliss** [comment]
Checking on it now. We are seeing increased 5xx errors at this time.

**Comment by rjgmail88** [comment]
Any updates?

**Comment by rjgmail88** [comment]
Our production bot is down over 8 hours. Please let me know if this is going to take long to fix so I can have some communication plan for the business.

**Comment by rjgmail88** [comment]
Please update us on this.

**Comment by rjgmail88** [comment]
@billbliss

**Comment by billbliss** [comment]
I have been communicating with Andrea Martini on this and he said this particular issue seems to be resolved.

**Comment by rjgmail88** [comment]
Error: POST to 'https://smba.trafficmanager.net/amer-client-ss.msg/v3/conversations/a%3A1hBGKzVwG1NG4tAyQeS7mKg4mNeYErz4rl2vJjNxIGQZJMy1eAiBBuKlPn-1w7-E2OwwB4Bm1imay1xLgRhMOrLRci2rzO1HZu6VUdNRNd0yVuGhgQfJPi02OyL71hJgr/activities/1529526049208' failed: [502] Bad Gateway


I am seeing this again today. Is there any permanent fix for this ? How should we handle this for productions bots ?

**Comment by rjgmail88** [comment]
I am seeing this again today. Is there any permanent fix for this ? How should we handle this for productions bots ?

**Comment by rjgmail88** [comment]
Here is the conversation Id 
       "conversationId" : "a:1qNZgTUu4ASGZkGKPYDtZque7ucUYmAuWHi7pVx2qfw7gtuHtEUybWEJnQDeZl31zAcglGMyoxKUik-VOpLKqGXop4UFTiQ70NZzkj49LHhNSeVlYFnJTCAjVVFtoViDt"

and error 


```
Error: POST to 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1qNZgTUu4ASGZkGKPYDtZque7ucUYmAuWHi7pVx2qfw7gtuHtEUybWEJnQDeZl31zAcglGMyoxKUik-VOpLKqGXop4UFTiQ70NZzkj49LHhNSeVlYFnJTCAjVVFtoViDt/activities/1530634672666' failed: [502] Bad Gateway

    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)

    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)

    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)

    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)

    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)

    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)

    at Request.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)

    at emitTwo (events.js:126:13)

    at Request.emit (events.js:214:7)

    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1157:10)

    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)

    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)

    at Request.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)

    at emitOne (events.js:116:13)

    at Request.emit (events.js:211:7)

    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1079:12)

    at Object.onceWrapper (events.js:313:30)

    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)

    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)

    at IncomingMessage.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)

    at emitNone (events.js:111:20)

```

**Comment by rjgmail88** [comment]
@billbliss , can you let us know if you are not managing this ? Can you route us to correct team ?

**Comment by rjgmail88** [comment]
I am getting 502 today.

Error: POST to 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1iW4wvOYbpsOa0fRviAt7tkak6uCn2ntSALF3V_EIkKLFpG92XFACmCu0r0d2vhp6l_UGX6vDIR86y74Oolw--daWsVyV5dzDEWfD8yeamr58T1zwqWCBiYSGHvewNC90/activities/1531615376540' failed: [502] Bad Gateway
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at Request.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1157:10)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at Request.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at IncomingMessage.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:345:33)
    at emitNone (events.js:111:20)

**Comment by andregouveia8** [comment]
I have the same issue.. On my webchat channel works fine, but on microsoft teams channel im getting this error 400... 🤒

**Comment by gnarsiMSFT** [comment]
@andregouveia8 Can you please let me know the timestamp when you saw the issue and bot ID to check on this?

**Comment by mohyt** [comment]
I am getting the same issue, I am using botbuilder-teams: 0.2.1.

**Comment by billbliss** [comment]
@mohyt what's your bot ID? We'll look for it in the logs.

**Comment by lecodespinner** [comment]
Hey @nguyendn!

It appears that your bot is trying to send a message to itself? Is the id below a typo or the intended behavior?
>  And then when we send a welcome message to `{ id:**'28:f56a1d76-2630-4200-bedc-fdff8a7672a6'** }`

Would you be able to provide more details on your end-to-end scenario? Also, could you capturing and provide the activity payload that your bot it sending? We can help you take a look from our end.

**Comment by nguyendn** [comment]
@lecodespinner sorry for the late reply. It seems we made a mistake. Thank you for your response.

**Comment by rjgmail88** [comment]
I have started seeing these errors again massively. We have been seeing since this issue is logged but now they are frequent. Any update on this ?

**Comment by laxmanj8666** [comment]
Error in Bot service with message ******* POST to 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1taZNBMcuPHBqvkmOy9FgPv4Q1vO_3SuKdONKI90861H421bCoVhHGNBegQiH4mufNoljJ5FNWyIArZSCygghZE-ZPjnF5ElIqrUIsBAZDClAi4_nYyYKwlp5wUdAR7_9/activities/1567951571075' failed: [400] Bad Request******* stackTrace *******  Error: POST to 'https://smba.trafficmanager.net/amer/v3/conversations/a%3A1taZNBMcuPHBqvkmOy9FgPv4Q1vO_3SuKdONKI90861H421bCoVhHGNBegQiH4mufNoljJ5FNWyIArZSCygghZE-ZPjnF5ElIqrUIsBAZDClAi4_nYyYKwlp5wUdAR7_9/activities/1567951571075' failed: [400] Bad Request


We started to see this message starting friday, it was working fine till friday morning. please help, we are seeing this issue in all our dev and prod bots.
