### ISSUE TITLE
TeamsMiddleware missing from npm package

### ISSUE THREAD

**Issue by KristianKarpati** [OfficeDev/BotBuilder-MicrosoftTeams#43]
I was unable to get  Strip bot mentions from the message text to make work 

```
TypeError: teams.StripBotAtMentions is not a constructor
    at Object.<anonymous> (C:\bot\app.js:71:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Comment by aharriswlu** [comment]
I got the same issue

**Comment by BillZengMSFT** [comment]
Hi @KristianKarpati and @aharriswlu , do you guys try example?

`var stripBotAtMentions = new teams.StripBotAtMentions();
bot.use(stripBotAtMentions);`

**Comment by aosolis** [comment]
StripBotAtMentions was added in v0.1.3, so please update the package to the latest first (v0.1.4).
