### ISSUE TITLE
New handlers are added in a way that breaks existing code at runtime

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/BotBuilder-MicrosoftTeams#92]
Before 0.1.7 added onSigninStateVerification(), bots had to handle signin/verifyState in their onInvoke handler. But with the upgrade to 0.1.6->0.1.7, existing code fails at runtime because signinStateVerificationHandler is missing. 

TypeError: Cannot read property 'bind' of undefined
    at TeamsChatConnector.dispatchEventOrQuery (c:\Projects\my-app\node_modules\botbuilder-teams\lib\TeamsChatConnector.js:212:81)
    at TeamsChatConnector.onDispatchEvents (c:\Projects\my-app\node_modules\botbuilder-teams\lib\TeamsChatConnector.js:183:18)
    at TeamsChatConnector.ChatConnector.dispatch (c:\Projects\my-app\node_modules\botbuilder\lib\bots\ChatConnector.js:466:18)
    at c:\Projects\my-app\node_modules\botbuilder\lib\bots\ChatConnector.js:149:27

There's no warning that this PATCH version increment would break existing code, and there are no release notes.

I think we should pass the event on to the onInvoke() handler if more specific handlers are missing, so that existing code continues to work, and developers can switch to the more specific handlers at their leisure.

**Comment by RamjotSingh** [comment]
@BillZengMSFT Can you please take a look at this?
